# -*- coding: utf-8 -*-
"""cis530_4o.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lYgZywZVm8aukuUC8P-fvz1L7B2N3g5R
"""

import torch
from transformers import pipeline
!pip install openai

# Commented out IPython magic to ensure Python compatibility.
import openai
# %set_env OPENAI_API_KEY=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

import pandas as pd
import re

questions = pd.read_csv('variants_data.csv')
questions = questions.sample(frac=1).reset_index(drop=True)
questions

def extract_final_number(text):
    # Find all numbers in the text
    numbers = re.findall(r'\b\d+\b', text)
    if numbers:
        # Convert the last number found to an integer
        return int(numbers[-1])
    return None  # Return None if no numbers are found

def answer_quest(question):
    prompt = '''
Q: Elsa has 5 apples. Anna has 2 more apples than Elsa. How
many apples do they have together?
A: Anna has 2 more apples than Elsa, so Anna has 2 + 5 = 7 apples. Elsa and Anna
have 5 + 7 = 12 apples together. The answer is 12.
Q: ''' + question + '\nA:'
    response = openai.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    long_ans = response.choices[0].message.content
    res = extract_final_number(long_ans)
    print(res)
    return res

our_list = [answer_quest(row[0]) for _, row in questions.iterrows()]

answers_list = [extract_final_number(row[2]) for _, row in questions.iterrows()]
answers_list

len(answers_list)

"""Export results to csv for evaluation with `scoring/score.py`"""

to_export = answers_list[:1123]
df = pd.DataFrame(to_export, columns=['Numbers'])
df.to_csv("correct_answers.csv", index=False)

"""saving to continue later"""

subset_df = questions.iloc[1123:]
subset_df.to_csv("in_progress_4o_original.csv", index=False)